#!/usr/bin/env bash

if [[ -e /var/cache/portage.eix ]]; then
    rsync -ca /var/cache/portage.eix /var/cache/previous.eix;
fi
eix-update
if [[ -e /var/cache/previous.eix ]]; then
    eix-diff;
fi

eix-remote update
